package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ModelEntry is one chain link — schema-identical to the Python version's
// dict entries, so config.json written by either implementation reads back
// fine in the other during a migration.
type ModelEntry struct {
	ProviderKey     string   `json:"provider_key"`
	Provider        string   `json:"provider"`
	Model           string   `json:"model"`
	MaxTokens       int      `json:"max_tokens"`
	ReasoningEffort string   `json:"reasoning_effort,omitempty"`
	Temperature     *float64 `json:"temperature,omitempty"`
	BaseURL         string   `json:"base_url,omitempty"`
	APIKeyEnv       string   `json:"api_key_env,omitempty"`
}

type Config struct {
	Models      map[string]ModelEntry  `json:"models"`
	TaskRouting map[string]interface{} `json:"task_routing"`
}

const ReasoningTask = "reasoning"

// RoutingKeys normalizes task_routing[task], which the Python side writes
// as either a bare string (single model) or an array (chain with fallbacks).
func (c *Config) RoutingKeys(task string) []string {
	if c == nil {
		return nil
	}
	v, ok := c.TaskRouting[task]
	if !ok {
		return nil
	}
	switch t := v.(type) {
	case string:
		return []string{t}
	case []interface{}:
		keys := make([]string, 0, len(t))
		for _, item := range t {
			if s, ok := item.(string); ok {
				keys = append(keys, s)
			}
		}
		return keys
	case []string:
		return t
	}
	return nil
}

// ChainFromConfig resolves the reasoning task's model + fallbacks in order.
func ChainFromConfig(cfg *Config) []ModelEntry {
	if cfg == nil {
		return nil
	}
	keys := cfg.RoutingKeys(ReasoningTask)
	chain := make([]ModelEntry, 0, len(keys))
	for _, k := range keys {
		if e, ok := cfg.Models[k]; ok {
			chain = append(chain, e)
		}
	}
	return chain
}

// ChainToConfig is the inverse: primary + fallbacks -> config.json shape.
func ChainToConfig(chain []ModelEntry) *Config {
	models := map[string]ModelEntry{}
	keys := make([]string, 0, len(chain))
	for i, e := range chain {
		key := ReasoningTask
		if i > 0 {
			key = fmt.Sprintf("%s_fallback_%d", ReasoningTask, i)
		}
		models[key] = e
		keys = append(keys, key)
	}
	var routing interface{} = keys
	if len(keys) == 1 {
		routing = keys[0]
	}
	return &Config{Models: models, TaskRouting: map[string]interface{}{ReasoningTask: routing}}
}

// --- persistence ---

var IgniteHome = func() string {
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".ignite")
}()

func ConfigPath() string { return filepath.Join(IgniteHome, "config.json") }
func EnvPath() string    { return filepath.Join(IgniteHome, ".env") }

func Exists() bool {
	_, err := os.Stat(ConfigPath())
	return err == nil
}

func Load() (*Config, error) {
	data, err := os.ReadFile(ConfigPath())
	if err != nil {
		return nil, err
	}
	var cfg Config
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", ConfigPath(), err)
	}
	return &cfg, nil
}

func Save(cfg *Config) error {
	if err := os.MkdirAll(IgniteHome, 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(ConfigPath(), data, 0o644)
}

func LoadEnvFile() map[string]string {
	env := map[string]string{}
	data, err := os.ReadFile(EnvPath())
	if err != nil {
		return env
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		k, v, ok := strings.Cut(line, "=")
		if ok && v != "" {
			env[k] = v
		}
	}
	return env
}

// SaveEnvFile writes every non-empty key in keys, TargetEnvKeys first (for
// a stable, diffable file) then any custom per-entry override names.
func SaveEnvFile(keys map[string]string) error {
	if err := os.MkdirAll(IgniteHome, 0o755); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# Generated by ignite — do not commit\n\n")

	written := map[string]bool{}
	for _, k := range TargetEnvKeys {
		if v := keys[k]; v != "" {
			b.WriteString(k + "=" + v + "\n")
			written[k] = true
		}
	}
	for k, v := range keys {
		if v == "" || written[k] {
			continue
		}
		b.WriteString(k + "=" + v + "\n")
	}
	return os.WriteFile(EnvPath(), []byte(b.String()), 0o600)
}

// LoadEnvVars collects every env var a container launch might need: the
// standard provider keys plus any custom api_key_env override used by an
// entry in cfg, read from .env first and the process environment as
// fallback (cfg may be nil if you just want the standard keys).
func LoadEnvVars(cfg *Config) map[string]string {
	file := LoadEnvFile()

	keys := map[string]bool{}
	for _, k := range TargetEnvKeys {
		keys[k] = true
	}
	if cfg != nil {
		for _, e := range cfg.Models {
			if e.APIKeyEnv != "" {
				keys[e.APIKeyEnv] = true
			}
		}
	}

	env := map[string]string{}
	for k := range keys {
		if v, ok := file[k]; ok && v != "" {
			env[k] = v
			continue
		}
		if v := os.Getenv(k); v != "" {
			env[k] = v
		}
	}
	return env
}

// --- model params ---

// ModelDefaultTemp resolves the effective default temperature: a per-model
// override if the ModelSpec declares one, else the provider's default.
func ModelDefaultTemp(caps ModelSpec, prov Provider) float64 {
	if caps.HasDefaultTemperature {
		return caps.DefaultTemperature
	}
	return prov.DefaultTemperature
}

// BuildModelParams mirrors build_model_params: reasoning models get an
// effort string, everything else gets a temperature.
func BuildModelParams(caps ModelSpec, effort string, defaultTemperature float64) (reasoningEffort string, temperature *float64) {
	if caps.SupportsReasoningEffort && effort != "" {
		return effort, nil
	}
	t := defaultTemperature
	return "", &t
}

// EntryFromProfile builds a persistable ModelEntry from a resolved profile.
func EntryFromProfile(providerKey, providerStr, model, baseURL, envKey string, caps ModelSpec, effort string, defaultTemperature float64) ModelEntry {
	reasoningEffort, temperature := BuildModelParams(caps, effort, defaultTemperature)
	return ModelEntry{
		ProviderKey:     providerKey,
		Provider:        providerStr,
		Model:           model,
		MaxTokens:       8192,
		ReasoningEffort: reasoningEffort,
		Temperature:     temperature,
		BaseURL:         baseURL,
		APIKeyEnv:       envKey,
	}
}
